# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin
  admin_username: admin
  admin_email: admin@example.com
  admin_password: 12345678
  secret_key_base: 93b32e41834777f9d4c0f18ea8b885553443df12ddda44acb9a36cfec30d1150cfe1f3a8341efbcfe6d0d5f02ccf7e96c91d30f2af7842f5a40f5ffe25df9635

test:
  admin_name: Admin
  admin_username: admin
  admin_email: admin@example.com
  admin_password: 12345678
  secret_key_base: 93b32e41834777f9d4c0f18ea8b885553443df12ddda44acb9a36cfec30d1150cfe1f3a8341efbcfe6d0d5f02ccf7e96c91d30f2af7842f5a40f5ffe25df9635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_username: <%= ENV["ADMIN_USERNAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
